config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :profiled_files, only: [:show]

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :files, class: ProfiledFile
  has_many :tags, class: ProfileTag

  def self.new_from_fluentd_record(params)
    profile = self.new

    profile.root_path = params['root_path']
    params['tags'].each_pair do |key, value|
      profile.tags << ProfileTag.new(key: key, value: value)
    end
    params['profile'].each_pair do |path, data|
      profile.files << ProfiledFile.new.tap do |file|
        records = []
        data.each_with_index do |datum, index|
          next if index == 0
          wall, cpu, calls, allocations = datum
          records << ProfileRecord.new(
            line: index,
            wall: wall,
            cpu: cpu,
            calls: calls,
            allocations: allocations,
          )
        end

        total_wall_time, child_wall_time, exclusive_wall_time, total_cpu_time, child_cpu_time, exclusive_cpu_time, allocations = data[0]

        file.path = path
        file.total_wall_time = total_wall_time
        file.child_wall_time = child_wall_time
        file.exclusive_wall_time = exclusive_wall_time
        file.total_cpu_time = total_cpu_time
        file.child_cpu_time = child_cpu_time
        file.exclusive_cpu_time = exclusive_cpu_time
        file.allocations = allocations
        file.records << records
      end
    end

    profile
  end

  def tag_value(key)
    tag = tags.where(key: key).first

    if tag
      tag.value
    else
      nil
    end
  end
end

app/models/profile_record.rb
class ProfileRecord < ActiveRecord::Base
  belongs_to :profiled_file

  def source
    profiled_file.source.lines[line - 1]
  end
end

app/models/profile_tag.rb
class ProfileTag < ActiveRecord::Base
  belongs_to :profile
end

app/models/profiled_file.rb
require 'pathname'

class ProfiledFile < ActiveRecord::Base
  belongs_to :profile
  has_many :records, class: ProfileRecord

  def source_file
    Rails.root.join(
      'sources',
      profile.tag_value('application'),
      profile.tag_value('revision'),
      relative_path)
  end

  def source
    @source ||= source_file.read
  end

  def relative_path
    Pathname.new(path).relative_path_from(
      Pathname.new(profile.root_path))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiled_files_controller.rb
class ProfiledFilesController < ApplicationController
  before_action :set_profiled_file, only: [:show]

  def show
  end

  private
    def set_profiled_file
      @profiled_file = ProfiledFile.find(params[:id])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new_from_fluentd_record(params['profile'])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params[:profile]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LineprofViewer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/profiled_files/show.html.erb
<table>
<tr>
  <th>calls</th>
  <th>wall</th>
  <th>cpu</th>
  <th>alloc</th>
</tr>
<% @profiled_file.records.order(:line).each do |record| %>
<% break unless record.source %>
<tr>
  <td><%= record.calls %></td>
  <td><%= record.wall %></td>
  <td><%= record.cpu %></td>
  <td><%= record.allocations %></td>
  <td style="background-color: #ff0000;">
    <pre style="margin: 0px; padding: 0px; background-color: transparent;"><%= record.source %></pre>
  </td>
</tr>
<% end %>
</table>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
<% @profile.files.each do |file| %>
<li><%= link_to file.relative_path.to_s, profiled_file_path(file) %></li>
<% end %>
</ul>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>